// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlatformDemo.Core.Data;

#nullable disable

namespace PlatformDemo.Core.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PlatformDemo.Core.Models.ServicePlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateOfPurchase")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ServicePlans");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateOfPurchase = new DateTime(2026, 2, 1, 14, 45, 48, 693, DateTimeKind.Local).AddTicks(277)
                        },
                        new
                        {
                            Id = 2,
                            DateOfPurchase = new DateTime(2026, 1, 29, 14, 45, 48, 693, DateTimeKind.Local).AddTicks(305)
                        },
                        new
                        {
                            Id = 3,
                            DateOfPurchase = new DateTime(2026, 1, 26, 14, 45, 48, 693, DateTimeKind.Local).AddTicks(306)
                        },
                        new
                        {
                            Id = 4,
                            DateOfPurchase = new DateTime(2026, 1, 23, 14, 45, 48, 693, DateTimeKind.Local).AddTicks(308)
                        },
                        new
                        {
                            Id = 5,
                            DateOfPurchase = new DateTime(2026, 1, 20, 14, 45, 48, 693, DateTimeKind.Local).AddTicks(309)
                        },
                        new
                        {
                            Id = 6,
                            DateOfPurchase = new DateTime(2026, 1, 17, 14, 45, 48, 693, DateTimeKind.Local).AddTicks(312)
                        },
                        new
                        {
                            Id = 7,
                            DateOfPurchase = new DateTime(2026, 1, 14, 14, 45, 48, 693, DateTimeKind.Local).AddTicks(313)
                        },
                        new
                        {
                            Id = 8,
                            DateOfPurchase = new DateTime(2026, 1, 11, 14, 45, 48, 693, DateTimeKind.Local).AddTicks(314)
                        },
                        new
                        {
                            Id = 9,
                            DateOfPurchase = new DateTime(2026, 1, 8, 14, 45, 48, 693, DateTimeKind.Local).AddTicks(315)
                        },
                        new
                        {
                            Id = 10,
                            DateOfPurchase = new DateTime(2026, 1, 5, 14, 45, 48, 693, DateTimeKind.Local).AddTicks(317)
                        },
                        new
                        {
                            Id = 11,
                            DateOfPurchase = new DateTime(2026, 1, 2, 14, 45, 48, 693, DateTimeKind.Local).AddTicks(317)
                        },
                        new
                        {
                            Id = 12,
                            DateOfPurchase = new DateTime(2025, 12, 30, 14, 45, 48, 693, DateTimeKind.Local).AddTicks(318)
                        });
                });

            modelBuilder.Entity("PlatformDemo.Core.Models.Timesheet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("ServicePlanId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ServicePlanId");

                    b.ToTable("Timesheets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Seeded work log - Ken - 1",
                            EndDateTime = new DateTime(2026, 2, 4, 14, 45, 48, 693, DateTimeKind.Local).AddTicks(479),
                            ServicePlanId = 1,
                            StartDateTime = new DateTime(2026, 2, 3, 14, 45, 48, 693, DateTimeKind.Local).AddTicks(476)
                        },
                        new
                        {
                            Id = 2,
                            Description = "Seeded work log - Ken - 1",
                            EndDateTime = new DateTime(2026, 2, 4, 14, 45, 48, 693, DateTimeKind.Local).AddTicks(495),
                            ServicePlanId = 1,
                            StartDateTime = new DateTime(2026, 2, 2, 21, 45, 48, 693, DateTimeKind.Local).AddTicks(494)
                        },
                        new
                        {
                            Id = 3,
                            Description = "Seeded work log - Ken - 1",
                            EndDateTime = new DateTime(2026, 2, 4, 14, 45, 48, 693, DateTimeKind.Local).AddTicks(497),
                            ServicePlanId = 1,
                            StartDateTime = new DateTime(2026, 2, 3, 1, 45, 48, 693, DateTimeKind.Local).AddTicks(497)
                        },
                        new
                        {
                            Id = 4,
                            Description = "Seeded work log - Ken - 2",
                            EndDateTime = new DateTime(2026, 2, 4, 14, 45, 48, 693, DateTimeKind.Local).AddTicks(499),
                            ServicePlanId = 2,
                            StartDateTime = new DateTime(2026, 2, 3, 14, 45, 48, 693, DateTimeKind.Local).AddTicks(499)
                        },
                        new
                        {
                            Id = 5,
                            Description = "Seeded work log - Ken - 2",
                            EndDateTime = new DateTime(2026, 2, 4, 14, 45, 48, 693, DateTimeKind.Local).AddTicks(502),
                            ServicePlanId = 2,
                            StartDateTime = new DateTime(2026, 2, 4, 8, 45, 48, 693, DateTimeKind.Local).AddTicks(501)
                        },
                        new
                        {
                            Id = 6,
                            Description = "Seeded work log - Ken - 2",
                            EndDateTime = new DateTime(2026, 2, 4, 14, 45, 48, 693, DateTimeKind.Local).AddTicks(504),
                            ServicePlanId = 2,
                            StartDateTime = new DateTime(2026, 2, 3, 5, 45, 48, 693, DateTimeKind.Local).AddTicks(503)
                        },
                        new
                        {
                            Id = 7,
                            Description = "Seeded work log - Ken - 2",
                            EndDateTime = new DateTime(2026, 2, 4, 14, 45, 48, 693, DateTimeKind.Local).AddTicks(505),
                            ServicePlanId = 2,
                            StartDateTime = new DateTime(2026, 2, 2, 20, 45, 48, 693, DateTimeKind.Local).AddTicks(505)
                        },
                        new
                        {
                            Id = 8,
                            Description = "Seeded work log - Ken - 3",
                            EndDateTime = new DateTime(2026, 2, 4, 14, 45, 48, 693, DateTimeKind.Local).AddTicks(538),
                            ServicePlanId = 3,
                            StartDateTime = new DateTime(2026, 2, 2, 21, 45, 48, 693, DateTimeKind.Local).AddTicks(538)
                        },
                        new
                        {
                            Id = 9,
                            Description = "Seeded work log - Ken - 3",
                            EndDateTime = new DateTime(2026, 2, 4, 14, 45, 48, 693, DateTimeKind.Local).AddTicks(541),
                            ServicePlanId = 3,
                            StartDateTime = new DateTime(2026, 2, 3, 13, 45, 48, 693, DateTimeKind.Local).AddTicks(540)
                        },
                        new
                        {
                            Id = 10,
                            Description = "Seeded work log - Ken - 3",
                            EndDateTime = new DateTime(2026, 2, 4, 14, 45, 48, 693, DateTimeKind.Local).AddTicks(544),
                            ServicePlanId = 3,
                            StartDateTime = new DateTime(2026, 2, 4, 1, 45, 48, 693, DateTimeKind.Local).AddTicks(543)
                        },
                        new
                        {
                            Id = 11,
                            Description = "Seeded work log - Ken - 3",
                            EndDateTime = new DateTime(2026, 2, 4, 14, 45, 48, 693, DateTimeKind.Local).AddTicks(545),
                            ServicePlanId = 3,
                            StartDateTime = new DateTime(2026, 2, 4, 11, 45, 48, 693, DateTimeKind.Local).AddTicks(545)
                        },
                        new
                        {
                            Id = 12,
                            Description = "Seeded work log - Ken - 4",
                            EndDateTime = new DateTime(2026, 2, 4, 14, 45, 48, 693, DateTimeKind.Local).AddTicks(547),
                            ServicePlanId = 4,
                            StartDateTime = new DateTime(2026, 2, 3, 9, 45, 48, 693, DateTimeKind.Local).AddTicks(546)
                        },
                        new
                        {
                            Id = 13,
                            Description = "Seeded work log - Ken - 4",
                            EndDateTime = new DateTime(2026, 2, 4, 14, 45, 48, 693, DateTimeKind.Local).AddTicks(549),
                            ServicePlanId = 4,
                            StartDateTime = new DateTime(2026, 2, 2, 21, 45, 48, 693, DateTimeKind.Local).AddTicks(549)
                        },
                        new
                        {
                            Id = 14,
                            Description = "Seeded work log - Ken - 4",
                            EndDateTime = new DateTime(2026, 2, 4, 14, 45, 48, 693, DateTimeKind.Local).AddTicks(551),
                            ServicePlanId = 4,
                            StartDateTime = new DateTime(2026, 2, 3, 14, 45, 48, 693, DateTimeKind.Local).AddTicks(551)
                        },
                        new
                        {
                            Id = 15,
                            Description = "Seeded work log - Ken - 4",
                            EndDateTime = new DateTime(2026, 2, 4, 14, 45, 48, 693, DateTimeKind.Local).AddTicks(553),
                            ServicePlanId = 4,
                            StartDateTime = new DateTime(2026, 2, 4, 2, 45, 48, 693, DateTimeKind.Local).AddTicks(552)
                        },
                        new
                        {
                            Id = 16,
                            Description = "Seeded work log - Ken - 5",
                            EndDateTime = new DateTime(2026, 2, 4, 14, 45, 48, 693, DateTimeKind.Local).AddTicks(555),
                            ServicePlanId = 5,
                            StartDateTime = new DateTime(2026, 2, 3, 7, 45, 48, 693, DateTimeKind.Local).AddTicks(554)
                        },
                        new
                        {
                            Id = 17,
                            Description = "Seeded work log - Ken - 7",
                            EndDateTime = new DateTime(2026, 2, 4, 14, 45, 48, 693, DateTimeKind.Local).AddTicks(559),
                            ServicePlanId = 7,
                            StartDateTime = new DateTime(2026, 2, 3, 6, 45, 48, 693, DateTimeKind.Local).AddTicks(558)
                        },
                        new
                        {
                            Id = 18,
                            Description = "Seeded work log - Ken - 7",
                            EndDateTime = new DateTime(2026, 2, 4, 14, 45, 48, 693, DateTimeKind.Local).AddTicks(563),
                            ServicePlanId = 7,
                            StartDateTime = new DateTime(2026, 2, 3, 17, 45, 48, 693, DateTimeKind.Local).AddTicks(562)
                        },
                        new
                        {
                            Id = 19,
                            Description = "Seeded work log - Ken - 7",
                            EndDateTime = new DateTime(2026, 2, 4, 14, 45, 48, 693, DateTimeKind.Local).AddTicks(564),
                            ServicePlanId = 7,
                            StartDateTime = new DateTime(2026, 2, 2, 17, 45, 48, 693, DateTimeKind.Local).AddTicks(563)
                        },
                        new
                        {
                            Id = 20,
                            Description = "Seeded work log - Ken - 8",
                            EndDateTime = new DateTime(2026, 2, 4, 14, 45, 48, 693, DateTimeKind.Local).AddTicks(566),
                            ServicePlanId = 8,
                            StartDateTime = new DateTime(2026, 2, 4, 4, 45, 48, 693, DateTimeKind.Local).AddTicks(565)
                        },
                        new
                        {
                            Id = 21,
                            Description = "Seeded work log - Ken - 8",
                            EndDateTime = new DateTime(2026, 2, 4, 14, 45, 48, 693, DateTimeKind.Local).AddTicks(569),
                            ServicePlanId = 8,
                            StartDateTime = new DateTime(2026, 2, 3, 19, 45, 48, 693, DateTimeKind.Local).AddTicks(568)
                        },
                        new
                        {
                            Id = 22,
                            Description = "Seeded work log - Ken - 8",
                            EndDateTime = new DateTime(2026, 2, 4, 14, 45, 48, 693, DateTimeKind.Local).AddTicks(570),
                            ServicePlanId = 8,
                            StartDateTime = new DateTime(2026, 2, 2, 17, 45, 48, 693, DateTimeKind.Local).AddTicks(569)
                        },
                        new
                        {
                            Id = 23,
                            Description = "Seeded work log - Ken - 8",
                            EndDateTime = new DateTime(2026, 2, 4, 14, 45, 48, 693, DateTimeKind.Local).AddTicks(572),
                            ServicePlanId = 8,
                            StartDateTime = new DateTime(2026, 2, 2, 17, 45, 48, 693, DateTimeKind.Local).AddTicks(571)
                        },
                        new
                        {
                            Id = 24,
                            Description = "Seeded work log - Ken - 8",
                            EndDateTime = new DateTime(2026, 2, 4, 14, 45, 48, 693, DateTimeKind.Local).AddTicks(573),
                            ServicePlanId = 8,
                            StartDateTime = new DateTime(2026, 2, 4, 8, 45, 48, 693, DateTimeKind.Local).AddTicks(573)
                        },
                        new
                        {
                            Id = 25,
                            Description = "Seeded work log - Ken - 9",
                            EndDateTime = new DateTime(2026, 2, 4, 14, 45, 48, 693, DateTimeKind.Local).AddTicks(575),
                            ServicePlanId = 9,
                            StartDateTime = new DateTime(2026, 2, 2, 18, 45, 48, 693, DateTimeKind.Local).AddTicks(574)
                        },
                        new
                        {
                            Id = 26,
                            Description = "Seeded work log - Ken - 9",
                            EndDateTime = new DateTime(2026, 2, 4, 14, 45, 48, 693, DateTimeKind.Local).AddTicks(577),
                            ServicePlanId = 9,
                            StartDateTime = new DateTime(2026, 2, 4, 5, 45, 48, 693, DateTimeKind.Local).AddTicks(577)
                        },
                        new
                        {
                            Id = 27,
                            Description = "Seeded work log - Ken - 9",
                            EndDateTime = new DateTime(2026, 2, 4, 14, 45, 48, 693, DateTimeKind.Local).AddTicks(579),
                            ServicePlanId = 9,
                            StartDateTime = new DateTime(2026, 2, 4, 11, 45, 48, 693, DateTimeKind.Local).AddTicks(578)
                        },
                        new
                        {
                            Id = 28,
                            Description = "Seeded work log - Ken - 11",
                            EndDateTime = new DateTime(2026, 2, 4, 14, 45, 48, 693, DateTimeKind.Local).AddTicks(581),
                            ServicePlanId = 11,
                            StartDateTime = new DateTime(2026, 2, 2, 15, 45, 48, 693, DateTimeKind.Local).AddTicks(580)
                        },
                        new
                        {
                            Id = 29,
                            Description = "Seeded work log - Ken - 11",
                            EndDateTime = new DateTime(2026, 2, 4, 14, 45, 48, 693, DateTimeKind.Local).AddTicks(586),
                            ServicePlanId = 11,
                            StartDateTime = new DateTime(2026, 2, 4, 10, 45, 48, 693, DateTimeKind.Local).AddTicks(585)
                        },
                        new
                        {
                            Id = 30,
                            Description = "Seeded work log - Ken - 11",
                            EndDateTime = new DateTime(2026, 2, 4, 14, 45, 48, 693, DateTimeKind.Local).AddTicks(587),
                            ServicePlanId = 11,
                            StartDateTime = new DateTime(2026, 2, 3, 8, 45, 48, 693, DateTimeKind.Local).AddTicks(587)
                        },
                        new
                        {
                            Id = 31,
                            Description = "Seeded work log - Ken - 11",
                            EndDateTime = new DateTime(2026, 2, 4, 14, 45, 48, 693, DateTimeKind.Local).AddTicks(589),
                            ServicePlanId = 11,
                            StartDateTime = new DateTime(2026, 2, 3, 23, 45, 48, 693, DateTimeKind.Local).AddTicks(588)
                        });
                });

            modelBuilder.Entity("PlatformDemo.Core.Models.Timesheet", b =>
                {
                    b.HasOne("PlatformDemo.Core.Models.ServicePlan", "ServicePlan")
                        .WithMany("Timesheets")
                        .HasForeignKey("ServicePlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServicePlan");
                });

            modelBuilder.Entity("PlatformDemo.Core.Models.ServicePlan", b =>
                {
                    b.Navigation("Timesheets");
                });
#pragma warning restore 612, 618
        }
    }
}
